# Generated by Django 4.2.7 on 2025-12-26 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique staff ID", max_length=20, unique=True
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administration"),
                            ("ACCOUNTS", "Accounts"),
                            ("LIBRARY", "Library"),
                            ("LAB", "Laboratory"),
                            ("TRANSPORT", "Transport"),
                            ("SECURITY", "Security"),
                            ("MAINTENANCE", "Maintenance"),
                            ("CANTEEN", "Canteen"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "designation",
                    models.CharField(help_text="Job title/position", max_length=100),
                ),
                ("joining_date", models.DateField()),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "ordering": ["department", "employee_id"],
            },
        ),
    ]
