# Generated by Django 4.2.7 on 2025-12-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolinfo",
            name="class_teacher_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Class Teacher Name (Override)"
            ),
        ),
        migrations.AddField(
            model_name="schoolinfo",
            name="class_teacher_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="school/signatures/",
                verbose_name="Class Teacher Signature",
            ),
        ),
        migrations.AddField(
            model_name="schoolinfo",
            name="principal_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Principal Name (Override)"
            ),
        ),
        migrations.AddField(
            model_name="schoolinfo",
            name="principal_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="school/signatures/",
                verbose_name="Principal Signature",
            ),
        ),
        migrations.AddField(
            model_name="schoolinfo",
            name="school_stamp",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="school/stamps/",
                verbose_name="School Stamp",
            ),
        ),
    ]
