# Generated by Django 4.2.7 on 2025-12-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="middle_name",
            field=models.CharField(
                blank=True, help_text="Middle name (optional)", max_length=50
            ),
        ),
    ]
