# Generated by Django 4.2.7 on 2025-12-26 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("GUARDIAN", "Legal Guardian"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Relationship to student",
                        max_length=20,
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, help_text="Current occupation", max_length=100
                    ),
                ),
                (
                    "employer",
                    models.CharField(
                        blank=True, help_text="Employer name", max_length=200
                    ),
                ),
                (
                    "office_address",
                    models.TextField(blank=True, help_text="Office address"),
                ),
                (
                    "annual_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual income (optional)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "alt_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Alternative contact person",
                        max_length=100,
                    ),
                ),
                ("alt_contact_phone", models.CharField(blank=True, max_length=17)),
                ("alt_contact_relation", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent",
                "verbose_name_plural": "Parents",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
    ]
