# Generated by Django 4.2.7 on 2025-12-26 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0002_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROMOTED", "Promoted"),
                            ("DETAINED", "Detained/Repeated"),
                            ("GRADUATED", "Graduated"),
                        ],
                        default="PROMOTED",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("promoted_on", models.DateField(auto_now_add=True)),
                (
                    "from_academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions_from",
                        to="classes.academicyear",
                    ),
                ),
                (
                    "from_class",
                    models.ForeignKey(
                        help_text="Previous class",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions_from",
                        to="classes.classroom",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="students.student",
                    ),
                ),
                (
                    "to_academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions_to",
                        to="classes.academicyear",
                    ),
                ),
                (
                    "to_class",
                    models.ForeignKey(
                        blank=True,
                        help_text="New class (null if graduated)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions_to",
                        to="classes.classroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
                "ordering": ["-promoted_on"],
            },
        ),
    ]
