# Generated by Django 4.2.7 on 2025-12-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teachers", "0001_initial"),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="class_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="classes.classroom",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_subjects",
                to="classes.subject",
            ),
        ),
        migrations.AddField(
            model_name="classsubject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_subjects",
                to="teachers.teacher",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="classes.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes_as_teacher",
                to="teachers.teacher",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classsubject",
            unique_together={("class_room", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("name", "stream", "academic_year")},
        ),
    ]
