# Generated by Django 4.2.7 on 2025-12-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="level",
            field=models.CharField(
                choices=[
                    ("PRIMARY", "Primary School"),
                    ("SECONDARY", "Secondary School"),
                    ("HIGH_SCHOOL", "High School"),
                    ("UNIVERSITY", "University Level"),
                ],
                max_length=20,
            ),
        ),
    ]
