# Generated by Django 4.2.7 on 2025-12-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Present", "Present"),
                            ("Absent", "Absent"),
                            ("Late", "Late"),
                            ("Excused", "Excused"),
                        ],
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("marked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-date", "student"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(help_text="First day of the month")),
                ("total_days", models.IntegerField(default=0)),
                ("present_days", models.IntegerField(default=0)),
                ("absent_days", models.IntegerField(default=0)),
                ("late_days", models.IntegerField(default=0)),
                ("excused_days", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Attendance Summary",
                "verbose_name_plural": "Attendance Summaries",
            },
        ),
    ]
