# Generated by Django 4.2.7 on 2025-12-26 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Unique teacher ID", max_length=20, unique=True
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        help_text="Highest educational qualification", max_length=200
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, help_text="Area of specialization", max_length=200
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(
                        default=0, help_text="Years of teaching experience"
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full Time"),
                            ("PART_TIME", "Part Time"),
                            ("CONTRACT", "Contract"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                ("joining_date", models.DateField(help_text="Date of joining")),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly salary",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "certifications",
                    models.TextField(
                        blank=True, help_text="Professional certifications"
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="Short biography")),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="teachers/resumes/"
                    ),
                ),
                (
                    "certificates",
                    models.FileField(
                        blank=True, null=True, upload_to="teachers/certificates/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Subjects this teacher can teach",
                        related_name="teachers",
                        to="classes.subject",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "ordering": ["employee_id"],
            },
        ),
    ]
