# Generated by Django 4.2.7 on 2025-12-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("MID_TERM", "Mid Term"),
                            ("FINAL", "Final Exam"),
                            ("QUIZ", "Quiz"),
                            ("ASSIGNMENT", "Assignment"),
                            ("PRACTICAL", "Practical"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="e.g., Term 1, Semester 1", max_length=20
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Are results published to students?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="classes.academicyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("room_number", models.CharField(blank=True, max_length=20)),
                ("max_marks", models.IntegerField(default=100)),
                ("pass_marks", models.IntegerField(default=40)),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.classroom",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="exams.exam",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Schedule",
                "verbose_name_plural": "Exam Schedules",
                "ordering": ["exam_date", "start_time"],
                "unique_together": {("exam", "class_room", "subject")},
            },
        ),
    ]
