# Generated by Django 4.2.7 on 2025-12-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_file",
            field=models.FileField(
                blank=True,
                help_text="Upload exam file (PDF or Word)",
                null=True,
                upload_to="exams/files/",
            ),
        ),
    ]
