# Generated by Django 4.2.7 on 2025-12-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_exam_exam_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("ONGOING", "Ongoing"),
                    ("COMPLETED", "Completed"),
                    ("POSTPONED", "Postponed"),
                ],
                default="SCHEDULED",
                help_text="Current status of the exam.",
                max_length=12,
            ),
        ),
    ]
