# Generated by Django 4.2.7 on 2025-12-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_exam_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="examschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("COMPLETED", "Completed"),
                    ("POSTPONED", "Postponed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SCHEDULED",
                help_text="Current status of the exam schedule.",
                max_length=12,
            ),
        ),
    ]
